[languages]
rust = ["rustfmt"]
go = ["gofmt"]
lua = ["stylua -s -"]
python = ["black --fast -"]
javascript = ["prettier --write"]
typescript = ["prettier --parser=typescript --write"]
vue = ["prettier --parser=vue --write"]
html = ["prettier --parser=html --write"]
css = ["prettier --parser=css --write"]
