" Specify a directory for plugins
call plug#begin('~/.vim/plugged')
" Plugins go here
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Vim Specific
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Tmux support
Plug 'tpope/vim-tbone' | Plug 'tmux-plugins/vim-tmux' | Plug 'tmux-plugins/vim-tmux-focus-events' | Plug 'christoomey/vim-tmux-navigator'
" Vim motions on speed
Plug 'easymotion/vim-easymotion' | Plug 'haya14busa/vim-easyoperator-line' | Plug 'haya14busa/vim-easyoperator-phrase'
" Defines a new text object representing lines of code at the same indent level
Plug 'michaeljsmith/vim-indent-object'
" Vim undo tree visualizer
Plug 'simnalamburt/vim-mundo'
" Interactive command execution
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
" Git wrapper and commit browser
Plug 'tpope/vim-fugitive' | Plug 'int3/vim-extradite'
" Displaying indent levels in code
Plug 'nathanaelkane/vim-indent-guides'
" Fuzzy file, buffer, mru, tag, etc finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' } | Plug 'junegunn/fzf.vim'
" Displays tags in a window
Plug 'majutsushi/tagbar'
" Multiple selection feature
Plug 'terryma/vim-multiple-cursors'
" Maintains a history of previous yanks, changes and deletes
Plug 'vim-scripts/YankRing.vim'
" Preview colours in source code while editing
Plug 'ap/vim-css-color'
" Edit Files using sudo or su or any other tool
Plug 'chrisbra/SudoEdit.vim'
" Shorthand notation
Plug 'junegunn/vim-easy-align'
" Comment stuff out
Plug 'tpope/vim-commentary'
" Quoting/parenthesizing made simple
Plug 'tpope/vim-surround'
" Insert or delete brackets, parens, quotes in pair
Plug 'jiangmiao/auto-pairs'
" Intelligently reopen files at your last edit position
Plug 'farmergreg/vim-lastplace'
" Status/tabline
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
" Continuously updated session files
Plug 'tpope/vim-obsession'
" Vim script for text filtering and alignment
Plug 'godlygeek/tabular'
" Run async shell commands
Plug 'skywind3000/asyncrun.vim'
" Allows toggling bookmarks per line
Plug 'MattesGroeger/vim-bookmarks'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General Programming
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Simple templates
Plug 'aperezdc/vim-template'
" A code-completion engine
Plug 'valloric/YouCompleteMe', { 'do': './install.py --clang-completer --js-completer --go-completer --rust-completer' }
" Generates config files for YouCompleteMe
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }
" Snippets engine and snippets
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets' | Plug 'jamescarr/snipmate-nodejs' | Plug 'sudar/vim-arduino-snippets'
" A collection of language packs for Vim
Plug 'sheerun/vim-polyglot'
" Asynchronous Lint Engine
Plug 'w0rp/ale'
" Format code with one button press
Plug 'chiel92/vim-autoformat'
" Dockerfile syntanx
Plug 'ekalinin/Dockerfile.vim'
" Docker commands
Plug 'ain/vim-docker'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Language Specific
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" Python
Plug 'python-mode/python-mode', { 'do': 'git submodule update --init --recursive' }
" Better code folding
Plug 'tmhedberg/SimpylFold', { 'for': 'python' }
" Work with python virtualenvs
Plug 'jmcantrell/vim-virtualenv', { 'for': 'python' }
" Vim plugin to sort python imports using isort
Plug 'fisadev/vim-isort', { 'for': 'python' }

"" JS/Node
" Tools and utilities for JS and Node.js
Plug 'moll/vim-node' | Plug 'jelera/vim-javascript-syntax' | Plug 'othree/javascript-libraries-syntax.vim' | Plug 'ternjs/tern_for_vim'

"" Latex
Plug 'lervag/vimtex'
" A Vim Plugin for Lively Previewing LaTeX PDF Output
Plug 'xuhdev/vim-latex-live-preview'

"" Vimscript
" Better Vimscript syntax highlighting
Plug 'vim-jp/syntax-vim-ex'

"" Todo.txt
Plug 'freitass/todo.txt-vim'

" All of your Plugins must be added before the following line
" Initialize plugin system
call plug#end()


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin configurations
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" YouCompleteMe
" Latex completion
if !exists('g:ycm_semantic_triggers')
let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme
" Shortcut for goto current definition
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

let g:ycm_autoclose_preview_window_after_insertion = 1

" Don't ask to load config
let g:ycm_confirm_extra_conf = 0

" Use 'Enter' for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = '<nop>'
let g:ulti_expand_or_jump_res = 0
function ExpandSnippetOrCarriageReturn()
    let l:snippet = UltiSnips#ExpandSnippetOrJump()
    if g:ulti_expand_or_jump_res > 0
        return l:snippet
    else
        return "\<CR>"
    endif
endfunction
inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrCarriageReturn()<CR>" : "\<CR>"

"" Artistic style
autocmd BufNewFile,BufRead *.cpp set formatprg=astyle
autocmd BufNewFile,BufRead *.hpp set formatprg=astyle
autocmd BufNewFile,BufRead *.c set formatprg=astyle
autocmd BufNewFile,BufRead *.h set formatprg=astyle

"" Airline
let g:airline_theme = 'zenburn'
let g:airline_powerline_fonts = 1

"" Multicursor
" Map start key separately from next key
let g:multi_cursor_start_key='<F6>'

"" Javascript
" Javascript libraries in use
let g:used_javascript_libs = 'jquery'

"" Tagbar
nmap <F8> :TagbarToggle<CR>

"" Autoformat
noremap <F3> :Autoformat<CR>
" Format on save
au BufWrite * :Autoformat
" Disable fallback to vim's indent file for certain files
autocmd FileType vim,tex let b:autoformat_autoindent=0
let g:autoformat_autoindent = 0
" let g:autoformat_retab = 0
" let g:autoformat_remove_trailing_spaces = 0
let g:formatters_python = ['yapf']

"" Vimtex
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_manual = 1
let g:vimtex_indent_enabled = 0
let g:vimtex_indent_on_ampersands = 0
let g:vimtex_indent_ignored_envs = ['document', 'figure']
let g:livepreview_engine = 'xelatex'

"" Asyncrunc
" Quick run via <F4>
nnoremap <F4> :call <SID>compile_and_run()<CR>

augroup ASYNCRUN
    autocmd!
    " Automatically open the quickfix window
    autocmd User AsyncRunStart call asyncrun#quickfix_toggle(15, 1)
augroup END

function! s:compile_and_run()
    exec 'w'
    if &filetype == 'c'
        exec "AsyncRun! gcc % -o %<; time ./%<"
    elseif &filetype == 'cpp'
       exec "AsyncRun! g++ -std=c++11 % -o %<; time ./%<"
    elseif &filetype == 'java'
       exec "AsyncRun! javac %; time java %<"
    elseif &filetype == 'sh'
       exec "AsyncRun! time bash %"
    elseif &filetype == 'python'
       exec "AsyncRun! time python %"
    endif
endfunction

"" Python-mode
let g:pymode_python = 'python3'

"" FZF
imap <c-x><c-o> <plug>(fzf-complete-line)
map <leader>b :Buffers<cr>
map <leader>f :Files<cr>
map <leader>g :GFiles<cr>
map <leader>t :Tags<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General configurations
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set laststatus=2
set showtabline=2
set tabstop=4
set shiftwidth=4
set expandtab
set t_Co=256
set term=screen-256color
set number
set ruler

" Ignore case unless contains uppercase
set ignorecase
set smartcase

" Tab completion criteria
set wildmode=longest,list,full

" Show completion options
set wildmenu

" Set utf8 as standard encoding
set encoding=utf8

" Files to ignore when expanding wildcard
set wildignore=*.pyc,*.o,*.so,*.a

" Ignore pyc files when expanding wildcards
let g:netrw_list_hide= ['.*\.pyc$', '\~', '.*\.o$', '.*\.so$', '.*\.a$']

" Turn backup off, since most stuff is in SVN, git etc anyway...
set nobackup
set nowritebackup
set noswapfile

set autoindent
set smartindent

" Return to last edit position when opening files (You want this!)
augroup last_position
    autocmd!
    autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
augroup END

" Turn on persistent undo
set undofile
set undodir=~/.vim/undo

" Allow VIM to use system clipboard
set clipboard=unnamedplus

" Where splits should occur
set splitbelow
set splitright

" In netrw, open selected file in new buffer
let g:netrw_liststyle=3

set background=dark

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Keymapping
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" Smart way to move between Vim splits & Tmux panes
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Close the current buffer
map <leader>bd :Bclose<cr>
" Close all the buffers
map <leader>ba :1,1000 bd!<cr>

" Remap VIM 0 to first non-blank character
map 0 ^

" Map <leader> & <localleader> to ','
map , <leader>
map , <localleader>

" TODO Make netrw more like NERDTree
" http://ivanbrennan.nyc/blog/2014/01/16/rigging-vims-netrw/
" Map Explorer Mode to <F2>
nmap <F2> :Explore<CR>

" Map ESC to jk in insert mode
inoremap jk <Esc>

"" Spell checking shortcuts
" Toggle spell checking
map <leader>ss :setlocal spell!<cr>
" Move to next misspelled word
map <leader>sn ]s
" Move to previous misspelled word
map <leader>sp [s
" Add word to own word list
map <leader>sa zg
" Suggest correct spelling
map <leader>s? z=

" Open vimrc
map <leader>ev :e ~/.vimrc<cr>
map <leader>vv :vsp ~/.vimrc<cr>
map <leader>pv :sp ~/.vimrc<cr>
" Source vimrc
map <leader>sv :source ~/.vimrc<cr>

" Toggle paste
map <F3> :setlocal paste!<cr>

" Easier moving of code blocks
" Try to go into visual mode (v), then select several lines of code here and
" then press ``>`` several times.
noremap < <gv  " better indentation
noremap > >gv  " better indentation

" Start latex live preview
map <F5> :LLPStartPreview<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
    exe 'normal mz'
    %s/\s\+$//ge
    exe 'normal `z'
endfunc
augroup delete_ws
    autocmd!
    autocmd BufWrite *.py :call DeleteTrailingWS()
    autocmd BufWrite *.coffee :call DeleteTrailingWS()
augroup END

" Don't close window, when deleting a buffer
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr('%')
    let l:alternateBufNum = bufnr('#')

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif

    if bufnr('%') == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute('bdelete! '.l:currentBufNum)
    endif
endfunction

" Open a new Tmux pane and start vim instance inside it
function! SplitPane(filename)
    silent execute '!tmux split-window -h "vim --servername ' . v:servername . ' '  . a:filename '"'
endfunction
command! -nargs=1 SPane call SplitPane(<f-args>)<cr>

colorscheme zenburn
let g:zenburn_transparent=1
