" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')

function! BuildColorCoded(info)
    execute "!" . "bash ~/.vim/installCCDeps.sh"
    if !isdirectory('build')
        call mkdir('build', 'p')
        echo "Created Color Coded build directory"
    endif

    cd build
    echo "Changed to build directory"
    silent !clear
    execute "!" . "cmake .."
    execute "!" . "make -j8"
    execute "!" . "make -j8 install"
    execute "!" . "make clean"
    execute "!" . "make clean_clang"
endfunction

function! InstallYCM(info)
    execute "!" . "bash ~/.vim/installYCM.sh"
endfunction

" Plugins go here
" Tmux support
Plug 'tpope/vim-tbone' | Plug 'tmux-plugins/vim-tmux' | Plug 'tmux-plugins/vim-tmux-focus-events' | Plug 'christoomey/vim-tmux-navigator'
" Vim motions on speed
Plug 'easymotion/vim-easymotion' | Plug 'haya14busa/vim-easyoperator-line' | Plug 'haya14busa/vim-easyoperator-phrase'
" Full path fuzzy file, buffer, mru, tag, ... finder
Plug 'ctrlpvim/ctrlp.vim'
" Defines a new text object representing lines of code at the same indent level
Plug 'michaeljsmith/vim-indent-object'
" Vim undo tree visualizer
Plug 'simnalamburt/vim-mundo'
" Interactive command execution
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
" Comment stuff out
Plug 'tpope/vim-commentary'			
" Git wrapper and commit browser
Plug 'tpope/vim-fugitive' | Plug 'int3/vim-extradite'
" Displaying indent levels in code
Plug 'nathanaelkane/vim-indent-guides'
" Fuzzy file, buffer, mru, tag, etc finder
Plug 'ctrlpvim/ctrlp.vim'
" Displays tags in a window
Plug 'majutsushi/tagbar'
" A vim plugin for libclang-based highlighting in C, C++, ObjC
if !has('nvim')
    Plug 'jeaye/color_coded', { 'do': function('BuildColorCoded') }
endif
" Open a Quickfix item in a window you choose
Plug 'yssl/QFEnter'
" A code-completion engine
Plug 'valloric/YouCompleteMe', { 'do': function('InstallYCM') }
" Generates config files for YouCompleteMe
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }
" Syntax checking
Plug 'scrooloose/syntastic'
" PEP8 syntax checking
Plug 'nvie/vim-flake8'
" Multiple selection feature 
Plug 'terryma/vim-multiple-cursors'
" Maintains a history of previous yanks, changes and deletes
Plug 'vim-scripts/YankRing.vim'
" Preview colours in source code while editing
Plug 'ap/vim-css-color'
" Work with python virtualenvs
Plug 'jmcantrell/vim-virtualenv'
" Snippets engine and snippes
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets' | Plug 'jamescarr/snipmate-nodejs'
" Edit Files using sudo or su or any other tool
Plug 'chrisbra/SudoEdit.vim'
" Shorthand notation
Plug 'junegunn/vim-easy-align'
" Quoting/parenthesizing made simple
Plug 'tpope/vim-surround'
" Simple templates
Plug 'aperezdc/vim-template'
" Status/tabline
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
" Better code folding
Plug 'tmhedberg/SimpylFold'
" Conform to PEP8 standards
Plug 'vim-scripts/indentpython.vim'
" Continuously updated session files
Plug 'tpope/vim-obsession'
" Tools and utilities for JS and Node.js
Plug 'moll/vim-node' | Plug 'jelera/vim-javascript-syntax' | Plug 'othree/javascript-libraries-syntax.vim' | Plug 'ternjs/tern_for_vim'
" Vim plugin for ROS development
Plug 'taketwo/vim-ros'
" CMake Interoperability in Vim
Plug 'jalcine/cmake.vim'

" All of your Plugins must be added before the following line
" Initialize plugin system
call plug#end()


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin configurations
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Syntastic Config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Flake8
let python_highlight_all=1

" YouCompleteMe
" Shortcut for goto current definition
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_server_python_interpreter = '/usr/bin/python2'

let g:ycm_autoclose_preview_window_after_insertion = 1

" Don't ask to load config 
let g:ycm_confirm_extra_conf = 0

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger="<c-v>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-n>"

" Artistic style
autocmd BufNewFile,BufRead *.cpp set formatprg=astyle
autocmd BufNewFile,BufRead *.hpp set formatprg=astyle
autocmd BufNewFile,BufRead *.c set formatprg=astyle
autocmd BufNewFile,BufRead *.h set formatprg=astyle

" Airline
let g:airline_theme = 'base16'
let g:airline_powerline_fonts = 1

" Map start key separately from next key
let g:multi_cursor_start_key='<F6>'

" SimpylFold
"Show docstrings for folded code
let g:SimpylFold_docstring_preview=1

" In order for SimpylFold to load in certain cases
autocmd BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr
autocmd BufWinLeave *.py setlocal foldexpr< foldmethod<

" JavaScript libraries in use
let g:used_javascript_libs = 'jquery'

" Tagbar
nmap <F8> :TagbarToggle<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General configurations
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set laststatus=2
set showtabline=2
set tabstop=4
set shiftwidth=4
set expandtab
set t_Co=256
if !has('nvim')
    set term=xterm-256color
endif
set number
set ruler
set wildignore+=*/tmp/*,*.so,*.swp,*.zip

" Tab completion criteria
set wildmode=longest,list,full

" Show completion options
set wildmenu

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Turn backup off, since most stuff is in SVN, git etc anyway...
set nobackup
set nowb
set noswapfile

set ai "Auto indent
set si "Smart indent

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

" Turn on persistent undo
set undofile
set undodir=~/.vim/undo

" Allow VIM to use system clipboard
set clipboard=unnamedplus

" Where splits should occur
set splitbelow
set splitright

set background=dark


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Keymapping
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" Smart way to move between windows
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Close the current buffer
map <leader>bd :Bclose<cr>

" Close all the buffers
map <leader>ba :1,1000 bd!<cr>

" Remap VIM 0 to first non-blank character
map 0 ^

" Map <leader> to ','
if has('nvim')
    let mapleader=";"
    let mapleader=","
    " Map <Esc> to exit terminal-mode:
    :tnoremap <Esc> <C-\><C-n>
    " Use `ALT+{h,j,k,l}` to navigate windows from any mode:
    :tnoremap <A-h> <C-\><C-N><C-w>h
    :tnoremap <A-j> <C-\><C-N><C-w>j
    :tnoremap <A-k> <C-\><C-N><C-w>k
    :tnoremap <A-l> <C-\><C-N><C-w>l
    :inoremap <A-h> <C-\><C-N><C-w>h
    :inoremap <A-j> <C-\><C-N><C-w>j
    :inoremap <A-k> <C-\><C-N><C-w>k
    :inoremap <A-l> <C-\><C-N><C-w>l
    :nnoremap <A-h> <C-w>h
    :nnoremap <A-j> <C-w>j
    :nnoremap <A-k> <C-w>k
    :nnoremap <A-l> <C-w>l
else
    map , <leader>
endif

" Map Explorer Mode to <F2>
nmap <F2> :Explore<CR>
let g:netrw_liststyle=3

" Map ESC to jk in insert mode
"imap jk <Esc>

 " Pressing ,ss will toggle and untoggle spell checking
map <leader>ss :setlocal spell!<cr>

" Shortcuts using <leader>
map <leader>sn ]s
map <leader>sp [s
map <leader>sa zg
map <leader>s? z=

" Open vimrc
map <leader>ev :e ~/.vimrc<cr>

" Source vimrc
map <leader>sv :source ~/.vimrc<cr>

" Toggle paste
map <F3> :setlocal paste!<cr>

" Easier moving of code blocks
" Try to go into visual mode (v), then select several lines of code here and
" then press ``>`` several times.
noremap < <gv  " better indentation
noremap > >gv  " better indentation

" Map Esc to jk
inoremap jk <Esc>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
    exe "normal mz"
    %s/\s\+$//ge
    exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()

" Don't close window, when deleting a buffer
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif

    if bufnr("%") == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute("bdelete! ".l:currentBufNum)
    endif
endfunction
