# Set prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set default shell and terminal
set-option -g default-shell /bin/zsh

# Start window and pane numbering at 1
set -g pane-base-index 1
set -g base-index 1
set-option -g renumber-windows on

# enable activity alerts
set-option -g visual-activity on
set-window-option -g monitor-activity on
set-option -g allow-rename off

# Act like Vim; use h,j,k,l to select panes and move the cursor
set-window-option -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# move current window left and right in the tab list, respectively.
bind '<' swap-window -t -1
bind '>' swap-window -t +1

# C-a C-b will swap to last used window
bind-key C-b last-window

# Split
set -g pane-active-border-style fg=colour234,bg=default
set -g pane-border-style fg=colour234,bg=default

# Status
set -g status on
set-option -g status-position bottom
set -g status-left ''
set -g status-right '#[fg=colour176,bold,bg=colour236,bold] %B #[fg=colour146,bold,bg=colour236,bold]%d, #[fg=colour173,bold,bg=colour236,bold]%Y#[fg=default] #[fg=colour234,bold,bg=colour12,bold] %R '
set -g status-right-length 100
set -g status-bg default
setw -g window-status-format '#[fg=colour236,bold,bg=colour180,bold] #I #[fg=colour180,bold,bg=colour236,bold] #W '
setw -g window-status-current-format '#[fg=colour180,bold,bg=colour236,bold] #I #[fg=colour236,bold,bg=colour180,bold] #W '

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# for vim
set -g @resurrect-strategy-vim 'session'

# in .tmux.conf
set -g @shell_mode 'vi'

# in .tmux.conf
set -g @yank_selection 'primary'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
