export EDITOR=vim
export TERM=screen-256color

eval "$(hub alias -s)"

export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=$HOME/workspace/python     

export GOROOT="$HOME/.local/go"
export PATH="$GOROOT/bin:$PATH"
export GOPATH="$HOME/workspace/go"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
eval "$(pyenv virtualenv-init -)"

