export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=$HOME/workspace/python     

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

source /opt/ros/kinetic/setup.zsh
